name: decog_gsk
description: "App for controlling Decog GSK001 Series"
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.9.2

assets:
  - "lib/assets/device_connected.png"
  - "lib/assets/device_disconnected.png"
  - "lib/assets/device_leak.png"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  supabase_flutter: ^2.10.3
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
  adaptive_icon_background: "#FFFFFF"  # Background color
  adaptive_icon_foreground: "lib/assets/logo.png"  # Your logo

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
